In [1]:
import pandas as pd

dt = pd.read_csv("HR_Workforce_Analysis_Cleaned_Data.csv")

In [2]:
dt.shape

(40000, 25)

In [5]:
dt["Monthly_Income"] = dt["Monthly_Income"].str.replace("₹", "", regex=False).str.replace(",", "", regex=False).astype(float)

dt["Annual_Income"] = dt["Annual_Income"].str.replace("₹", "", regex=False).str.replace(",", "", regex=False).astype(float)

In [6]:
dt.dtypes

Employee_ID                       str
Age                             int64
Gender                            str
Marital_Status                    str
Department                        str
Job_Role                          str
Job_Level                       int64
Education                         str
Education_Field                   str
Monthly_Income                float64
Annual_Income                 float64
Total_Working_Years             int64
Years_At_Company                int64
Years_In_Current_Role           int64
Years_Since_Last_Promotion      int64
Years_With_Current_Manager      int64
Distance_From_Home              int64
Business_Travel                   str
Overtime                          str
Job_Satisfaction                int64
Work_Life_Balance               int64
Performance_Rating              int64
Training_Times_Last_Year        int64
Attrition                         str
Satisfaction_Score            float64
dtype: object

In [8]:
dt.describe()

,Age,Job_Level,Monthly_Income,Annual_Income,Total_Working_Years,Years_At_Company,Years_In_Current_Role,Years_Since_Last_Promotion,Years_With_Current_Manager,Distance_From_Home,Job_Satisfaction,Work_Life_Balance,Performance_Rating,Training_Times_Last_Year,Satisfaction_Score
count,40000.000000,40000.000000,40000.000000,4.000000e+04,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.00000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000
mean,34.079000,1.562975,72056.844775,8.646821e+05,13.295075,7.299200,4.556225,2.376450,3.995225,10.98025,2.814025,2.801450,2.246350,2.595500,2.706812
std,7.849586,0.797684,24063.538918,2.887625e+05,8.362114,5.330951,3.610514,2.279806,3.267969,7.28544,0.944040,0.894761,0.588065,1.603027,0.574541
min,18.000000,1.000000,18000.000000,2.160000e+05,0.000000,0.000000,0.000000,0.000000,0.000000,1.00000,1.000000,1.000000,1.000000,0.000000,1.000000
25%,29.000000,1.000000,54240.500000,6.508860e+05,7.000000,3.000000,2.000000,1.000000,2.000000,6.00000,2.000000,2.000000,2.000000,1.000000,2.300000
50%,34.000000,1.000000,67090.000000,8.050800e+05,13.000000,6.000000,4.000000,2.000000,3.000000,9.00000,3.000000,3.000000,2.000000,2.000000,2.700000
75%,39.000000,2.000000,86797.000000,1.041564e+06,19.000000,10.000000,6.000000,3.000000,6.000000,15.00000,4.000000,3.000000,2.000000,4.000000,3.000000
max,60.000000,5.000000,178943.000000,2.147316e+06,40.000000,34.000000,20.000000,15.000000,17.000000,40.00000,4.000000,4.000000,4.000000,8.000000,4.000000

In [12]:
dt["Department"] = dt["Department"].str.title()

dt["Department"] = dt["Department"].replace("It", "IT")

In [13]:
dt["Department"].value_counts()

Department
Research & Development    9243
Sales                     8777
IT                        5603
Operations                5566
Finance                   4037
Marketing                 3566
Human Resources           3208
Name: count, dtype: int64

In [15]:
dt["Attrition"].value_counts()

Attrition
No     32490
Yes     7510
Name: count, dtype: int64

In [16]:
dt["Attrition"].value_counts(normalize=True) * 100

Attrition
No     81.225
Yes    18.775
Name: proportion, dtype: float64

In [17]:
pd.crosstab(dt["Department"], dt["Attrition"], normalize="index") * 100

Attrition                      No        Yes
Department
Finance                 81.174139  18.825861
Human Resources         81.078554  18.921446
IT                      81.295734  18.704266
Marketing               80.678632  19.321368
Operations              81.135465  18.864535
Research & Development  81.553608  18.446392
Sales                   81.189472  18.810528

In [18]:
pd.crosstab(dt["Department"], dt["Attrition"])

Attrition                 No   Yes
Department
Finance                 3277   760
Human Resources         2601   607
IT                      4555  1048
Marketing               2877   689
Operations              4516  1050
Research & Development  7538  1705
Sales                   7126  1651

In [19]:
dt["Job_Role"].value_counts()

Job_Role
Lab Technician          3134
R&D Manager             3058
Research Scientist      3051
Sales Manager           2940
Sales Representative    2932
Sales Executive         2905
Operations Manager      1880
Operations Executive    1877
Software Analyst        1877
IT Manager              1868
IT Support              1858
Operations Analyst      1809
Finance Manager         1352
Accountant              1349
Financial Analyst       1336
Marketing Executive     1270
Marketing Analyst       1156
Marketing Manager       1140
HR Specialist           1092
HR Executive            1062
HR Manager              1054
Name: count, dtype: int64

In [20]:
pd.crosstab(dt["Job_Role"], dt["Attrition"], normalize="index") * 100

Attrition                    No        Yes
Job_Role
Accountant            81.838399  18.161601
Finance Manager       81.213018  18.786982
Financial Analyst     80.464072  19.535928
HR Executive          80.696798  19.303202
HR Manager            79.696395  20.303605
HR Specialist         82.783883  17.216117
IT Manager            82.494647  17.505353
IT Support            80.785791  19.214209
Lab Technician        82.195278  17.804722
Marketing Analyst     80.190311  19.809689
Marketing Executive   80.078740  19.921260
Marketing Manager     81.842105  18.157895
Operations Analyst    80.431177  19.568823
Operations Executive  82.418753  17.581247
Operations Manager    80.531915  19.468085
R&D Manager           81.687377  18.312623
Research Scientist    80.760406  19.239594
Sales Executive       82.409639  17.590361
Sales Manager         79.761905  20.238095
Sales Representative  81.412005  18.587995
Software Analyst      80.607352  19.392648

In [21]:
pd.crosstab(dt["Job_Role"], dt["Attrition"])

Attrition               No  Yes
Job_Role
Accountant            1104  245
Finance Manager       1098  254
Financial Analyst     1075  261
HR Executive           857  205
HR Manager             840  214
HR Specialist          904  188
IT Manager            1541  327
IT Support            1501  357
Lab Technician        2576  558
Marketing Analyst      927  229
Marketing Executive   1017  253
Marketing Manager      933  207
Operations Analyst    1455  354
Operations Executive  1547  330
Operations Manager    1514  366
R&D Manager           2498  560
Research Scientist    2464  587
Sales Executive       2394  511
Sales Manager         2345  595
Sales Representative  2387  545
Software Analyst      1513  364

In [22]:
dt["Age_Group"] = pd.cut(
    dt["Age"],
    bins=[17, 25, 35, 45, 60],
    labels=["18-25", "26-35", "36-45", "46-60"]
)

In [23]:
pd.crosstab(dt["Age_Group"], dt["Attrition"], normalize="index") * 100

Attrition         No        Yes
Age_Group
18-25      73.214595  26.785405
26-35      81.377819  18.622181
36-45      83.425493  16.574507
46-60      85.452119  14.547881

In [24]:
pd.crosstab(dt["Age_Group"], dt["Attrition"])

Attrition     No   Yes
Age_Group
18-25       4234  1549
26-35      13927  3187
36-45      11768  2338
46-60       2561   436

In [25]:
dt["Job_Level"].value_counts().sort_index()

Job_Level
1    24087
2    10423
3     4457
4      950
5       83
Name: count, dtype: int64

In [26]:
pd.crosstab(dt["Job_Level"], dt["Attrition"], normalize="index") * 100

Attrition         No        Yes
Job_Level
1          79.337402  20.662598
2          83.862612  16.137388
3          83.643707  16.356293
4          88.421053  11.578947
5          85.542169  14.457831

In [27]:
pd.crosstab(dt["Job_Level"], dt["Attrition"])

Attrition     No   Yes
Job_Level
1          19110  4977
2           8741  1682
3           3728   729
4            840   110
5             71    12

In [30]:
dt["Overtime"].value_counts()

Overtime
No     28978
Yes    11022
Name: count, dtype: int64

In [29]:
dt["Overtime"] = dt["Overtime"].str.strip().str.title()

In [31]:
pd.crosstab(dt["Overtime"], dt["Attrition"], normalize="index") * 100

Attrition         No        Yes
Overtime
No         83.956795  16.043205
Yes        74.042823  25.957177

In [32]:
pd.crosstab(dt["Overtime"], dt["Attrition"])

Attrition     No   Yes
Overtime
No         24329  4649
Yes         8161  2861

In [33]:
dt["Job_Satisfaction"].value_counts().sort_index()

Job_Satisfaction
1     4728
2     8051
3    17153
4    10068
Name: count, dtype: int64

In [34]:
pd.crosstab(dt["Job_Satisfaction"], dt["Attrition"], normalize="index") * 100

Attrition                No        Yes
Job_Satisfaction
1                 77.876481  22.123519
2                 77.890945  22.109055
3                 82.329622  17.670378
4                 83.581645  16.418355

In [35]:
pd.crosstab(dt["Job_Satisfaction"], dt["Attrition"])

Attrition            No   Yes
Job_Satisfaction
1                  3682  1046
2                  6271  1780
3                 14122  3031
4                  8415  1653

In [36]:
pd.crosstab(dt["Work_Life_Balance"], dt["Attrition"], normalize="index") * 100

Attrition                 No        Yes
Work_Life_Balance
1                  79.655946  20.344054
2                  78.919661  21.080339
3                  82.531330  17.468670
4                  81.492402  18.507598

In [37]:
pd.crosstab(
    pd.cut(dt["Years_At_Company"], bins=[-1, 2, 5, 10, 20, 40],
           labels=["0-2", "3-5", "6-10", "11-20", "21+"]),
    dt["Attrition"],
    normalize="index"
) * 100

Attrition                No        Yes
Years_At_Company
0-2               74.170647  25.829353
3-5               81.088421  18.911579
6-10              82.902026  17.097974
11-20             84.534038  15.465962
21+               85.984848  14.015152

In [38]:
pd.crosstab(
    pd.qcut(dt["Monthly_Income"], 4),
    dt["Attrition"],
    normalize="index"
) * 100

Attrition                    No        Yes
Monthly_Income
(17999.999, 54240.5]  77.150000  22.850000
(54240.5, 67090.0]    80.501950  19.498050
(67090.0, 86797.0]    82.630000  17.370000
(86797.0, 178943.0]   84.618462  15.381538

In [39]:
pd.crosstab(
    dt["Performance_Rating"],
    dt["Attrition"],
    normalize="index"
) * 100

Attrition                  No        Yes
Performance_Rating
1                   80.589366  19.410634
2                   81.214679  18.785321
3                   81.465994  18.534006
4                   80.816078  19.183922